name: CI - Pages & Snapshots

on:
  push:
    branches: [ "main" ]
    tags:
      - "snapshot-*"
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy-pages:
    needs: build-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

  snapshot-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare snapshot
        run: |
          mkdir -p artifacts
          SNAP_NAME="site-${{ github.run_id }}-${{ github.sha }}.zip"
          zip -r "artifacts/$SNAP_NAME" . -x "*.git*" "snapshots/*" ".github/*"
          echo "SNAP_NAME=$SNAP_NAME" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SNAP_NAME }}
          path: artifacts/${{ env.SNAP_NAME }}
      - name: Create release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/${{ env.SNAP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
